---
title: "ARIMA"
output: pdf_document
---

library(forecast)
library(readxl)
library(timeSeries)

path <- "../data/ARIMA.xls"
df <- read_excel(path, sheet = "data")

# SUBSETS
rpd <- df$RPD
dpc <- df$DPC

# DATES
date_min <- min(df$Ano)
date_max <- max(df$Ano)

# TS OBJECTS
rpd_ts <- ts(rpd, start = c(date_min, 1), end = c(date_max, 4), frequency = 4)
dpc_ts <- ts(dpc, start = c(date_min, 1), end = c(date_max, 4), frequency = 4)

# CHARTS
autoplot(rpd_ts) + theme_bw() + labs(x = "Trimestre", y = "Valor", title = "RPD")
autoplot(dpc_ts) + theme_bw() + labs(x = "Trimestre", y = "Valor", title = "DPC")

# STATIONARITY TEST
adf.test(rpd_ts)
ggAcf(rpd_ts) + theme_bw() + labs(title = "RPD")
adf.test(diff(rpd_ts)) # I = 1
ggAcf(diff(rpd_ts)) + theme_bw() + labs(title = "RPD em primeira diferença")

adf.test(dpc_ts)
ggAcf(dpc_ts) + theme_bw() + labs(title = "DPC")
adf.test(diff(dpc_ts))
ggAcf(diff(dpc_ts)) + theme_bw() + labs(title = "DPC em primeira diferença")
adf.test(diff(diff(dpc_ts))) # I = 2
ggAcf(diff(diff(dpc_ts))) + theme_bw() + labs(title = "RPD")

